<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Master_Komponen_Model extends CI_Model
{

    public $table = 'tbl_master_komponen';
    public $id = 'id_komponen';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
/*    function json() {
        $this->datatables->select('id_komponen,jenis_komponen,nama_komponen,keterangan,gambar_komponen');
        $this->datatables->from('tbl_master_komponen');
        //add this line for join
        $this->datatables->join('tbl_kategori_komponen', 'tbl_master_komponen.jenis_komponen = tbl_kategori_komponen.jenis_komponen');
        $this->datatables->add_column('action',anchor(site_url('masterkomponen/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('masterkomponen/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_komponen');
        return $this->datatables->generate();
    }*/
    

    // get all
    function get_all()
    {
        $this->db->join('tbl_kategori_komponen', 'tbl_master_komponen.jenis_komponen = tbl_kategori_komponen.jenis_komponen', 'inner');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    } 

    //get kategori dari tbl_kategori_komponen
    public function get_kategori()
    {
      $sql =  $this->db->get('tbl_kategori_komponen');
      return $sql->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('tbl_kategori_komponen', 'tbl_master_komponen.jenis_komponen = tbl_kategori_komponen.jenis_komponen', 'inner');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->like('id_komponen', $q);
    $this->db->or_like('jenis_komponen', $q);
	$this->db->or_like('nama_komponen', $q);
    $this->db->or_like('keterangan', $q);
    $this->db->or_like('gambar_komponen', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->order_by($this->id, $this->order);
    $this->db->like('id_komponen', $q);
    $this->db->or_like('jenis_komponen', $q);
    $this->db->or_like('nama_komponen', $q);
    $this->db->or_like('keterangan', $q);
    $this->db->or_like('gambar_komponen', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Master_Komponen_Model.php */
/* Location: ./application/models/Master_Komponen_Model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-04 10:50:27 */
/* http://harviacode.com */