<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Produk_Rancangan_Model extends CI_Model
{

    public $table = 'tbl_produk_rancangan';
    public $id = 'id_produk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    /*function json() {
        $this->datatables->select('id_produk,nama_produk,id_komponen,jml_komponen');
        $this->datatables->from('tbl_produk_rancangan');
        //$this->datatables->add_column('is_aktif', '$1', 'rename_string_is_aktif(is_aktif)');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_menu.field = table2.field');
      //$this->datatables->join('tbl_komponen', 'tbl_komponen_keluar.id_komponen a = tbl_komponen.id_komponen b');
        $this->datatables->add_column('action',anchor(site_url('produkrancangan/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('produkrancangan/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_produk');
        return $this->datatables->generate();
    }*/
    
    



    // get all
     function get_all()
    {
        $this->db->join('tbl_master_komponen', 'tbl_produk_rancangan.id_komponen = tbl_master_komponen.id_komponen', 'inner');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    } 
    public function get_komponen()
    {
      $sql =  $this->db->get('tbl_master_komponen');
      return $sql->result();
    }
    // get data by id
    function get_by_id($id)
    {
        $this->db->join('tbl_master_komponen', 'tbl_produk_rancangan.id_komponen = tbl_master_komponen.id_komponen', 'inner');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_menu', $q);
	$this->db->or_like('title', $q);
	$this->db->or_like('url', $q);
	$this->db->or_like('icon', $q);
	$this->db->or_like('is_main_menu', $q);
	$this->db->or_like('is_aktif', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_menu', $q);
	$this->db->or_like('title', $q);
	$this->db->or_like('url', $q);
	$this->db->or_like('icon', $q);
	$this->db->or_like('is_main_menu', $q);
	$this->db->or_like('is_aktif', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function detailproduk($id='')
           {
              if($id){
                  $this->db->where('id_produk',$id);
              }
              $sql = $this->db->query("SELECT DISTINCT tbl_produk_rancangan.id_produk,tbl_produk_rancangan.nama_produk FROM  `tbl_produk_rancangan`;");
              return $sql->result();
           }

    function detailread($id='')
           {
              $sql = $this->db->query("SELECT tbl_produk_rancangan.id_produk,tbl_produk_rancangan.nama_produk, tbl_master_komponen.nama_komponen, tbl_produk_rancangan.jml_komponen FROM `tbl_produk_rancangan` JOIN `tbl_master_komponen` ON tbl_master_komponen.id_komponen = tbl_produk_rancangan.id_komponen WHERE id_produk = '".$id."' ");
              return $sql->result();
           }

}

/* End of file Menu_model.php */
/* Location: ./application/models/Menu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-04 10:50:27 */
/* http://harviacode.com */